//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUIClient.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization_en_US {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization_en_US() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("GUIClient.Resources.Localization_en_US", typeof(Localization_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        internal static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        internal static string Sys {
            get {
                return ResourceManager.GetString("Sys", resourceCulture);
            }
        }
        
        internal static string OperationalSystem {
            get {
                return ResourceManager.GetString("OperationalSystem", resourceCulture);
            }
        }
        
        internal static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        internal static string NoRegistrationMSG {
            get {
                return ResourceManager.GetString("NoRegistrationMSG", resourceCulture);
            }
        }
        
        internal static string RegistrationErrorMSG {
            get {
                return ResourceManager.GetString("RegistrationErrorMSG", resourceCulture);
            }
        }
        
        internal static string RegistrationNotAcceptedMSG {
            get {
                return ResourceManager.GetString("RegistrationNotAcceptedMSG", resourceCulture);
            }
        }
        
        internal static string NotAccepted {
            get {
                return ResourceManager.GetString("NotAccepted", resourceCulture);
            }
        }
        
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        internal static string Environment {
            get {
                return ResourceManager.GetString("Environment", resourceCulture);
            }
        }
        
        internal static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        internal static string NotImplementedMSG {
            get {
                return ResourceManager.GetString("NotImplementedMSG", resourceCulture);
            }
        }
        
        internal static string SelectAuthenticationMSG {
            get {
                return ResourceManager.GetString("SelectAuthenticationMSG", resourceCulture);
            }
        }
        
        internal static string ApplicationMN {
            get {
                return ResourceManager.GetString("ApplicationMN", resourceCulture);
            }
        }
        
        internal static string ExitMN {
            get {
                return ResourceManager.GetString("ExitMN", resourceCulture);
            }
        }
        
        internal static string WelcomeMSG {
            get {
                return ResourceManager.GetString("WelcomeMSG", resourceCulture);
            }
        }
        
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        internal static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        internal static string Machine {
            get {
                return ResourceManager.GetString("Machine", resourceCulture);
            }
        }
        
        internal static string Computer {
            get {
                return ResourceManager.GetString("Computer", resourceCulture);
            }
        }
        
        internal static string LoggedAccount {
            get {
                return ResourceManager.GetString("LoggedAccount", resourceCulture);
            }
        }
        
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        internal static string ClientApproveErrorMSG {
            get {
                return ResourceManager.GetString("ClientApproveErrorMSG", resourceCulture);
            }
        }
        
        internal static string ClientRejectErrorMSG {
            get {
                return ResourceManager.GetString("ClientRejectErrorMSG", resourceCulture);
            }
        }
        
        internal static string ClientDeleteConfirmationMSG {
            get {
                return ResourceManager.GetString("ClientDeleteConfirmationMSG", resourceCulture);
            }
        }
        
        internal static string RisksOverTime {
            get {
                return ResourceManager.GetString("RisksOverTime", resourceCulture);
            }
        }
        
        internal static string Assessments {
            get {
                return ResourceManager.GetString("Assessments", resourceCulture);
            }
        }
        
        internal static string Answers {
            get {
                return ResourceManager.GetString("Answers", resourceCulture);
            }
        }
        
        internal static string Questions {
            get {
                return ResourceManager.GetString("Questions", resourceCulture);
            }
        }
        
        internal static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        internal static string AssessmentNameInvalidMSG {
            get {
                return ResourceManager.GetString("AssessmentNameInvalidMSG", resourceCulture);
            }
        }
        
        internal static string AssessmentNameExistsMSG {
            get {
                return ResourceManager.GetString("AssessmentNameExistsMSG", resourceCulture);
            }
        }
        
        internal static string ErrorCreatingAssessmentMSG {
            get {
                return ResourceManager.GetString("ErrorCreatingAssessmentMSG", resourceCulture);
            }
        }
        
        internal static string ConfirmDeleteAssessmentMSG {
            get {
                return ResourceManager.GetString("ConfirmDeleteAssessmentMSG", resourceCulture);
            }
        }
        
        internal static string ErrorDeletingAssessmentMSG {
            get {
                return ResourceManager.GetString("ErrorDeletingAssessmentMSG", resourceCulture);
            }
        }
        
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        internal static string Risk {
            get {
                return ResourceManager.GetString("Risk", resourceCulture);
            }
        }
        
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        internal static string AnswerAlreadyExistsMSG {
            get {
                return ResourceManager.GetString("AnswerAlreadyExistsMSG", resourceCulture);
            }
        }
        
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        internal static string ErrorSavingQuestionMSG {
            get {
                return ResourceManager.GetString("ErrorSavingQuestionMSG", resourceCulture);
            }
        }
        
        internal static string QuestionAlreadyExistsMSG {
            get {
                return ResourceManager.GetString("QuestionAlreadyExistsMSG", resourceCulture);
            }
        }
        
        internal static string ErrorSavingAnswersMSG {
            get {
                return ResourceManager.GetString("ErrorSavingAnswersMSG", resourceCulture);
            }
        }
        
        internal static string QuestionDoesNotExistsMSG {
            get {
                return ResourceManager.GetString("QuestionDoesNotExistsMSG", resourceCulture);
            }
        }
        
        internal static string ConfirmDeleteAssessmentQuestionMSG {
            get {
                return ResourceManager.GetString("ConfirmDeleteAssessmentQuestionMSG", resourceCulture);
            }
        }
        
        internal static string ErrorDeletingAssessmentQuestionMSG {
            get {
                return ResourceManager.GetString("ErrorDeletingAssessmentQuestionMSG", resourceCulture);
            }
        }
        
        internal static string ErrorOpeningExternalBrowserMSG {
            get {
                return ResourceManager.GetString("ErrorOpeningExternalBrowserMSG", resourceCulture);
            }
        }
        
        internal static string SAMLAuthenticationTimeoutMSG {
            get {
                return ResourceManager.GetString("SAMLAuthenticationTimeoutMSG", resourceCulture);
            }
        }
        
        internal static string LogoutQuit {
            get {
                return ResourceManager.GetString("LogoutQuit", resourceCulture);
            }
        }
        
        internal static string ControlStatistics {
            get {
                return ResourceManager.GetString("ControlStatistics", resourceCulture);
            }
        }
        
        internal static string Maturity {
            get {
                return ResourceManager.GetString("Maturity", resourceCulture);
            }
        }
        
        internal static string DesiredMaturity {
            get {
                return ResourceManager.GetString("DesiredMaturity", resourceCulture);
            }
        }
        
        internal static string ControlRisk {
            get {
                return ResourceManager.GetString("ControlRisk", resourceCulture);
            }
        }
        
        internal static string StrRiskPanel {
            get {
                return ResourceManager.GetString("StrRiskPanel", resourceCulture);
            }
        }
        
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        internal static string SubmissionDate {
            get {
                return ResourceManager.GetString("SubmissionDate", resourceCulture);
            }
        }
    }
}
