//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUIClient.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization_pt_BR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization_pt_BR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GUIClient.Resources.Localization.pt-BR", typeof(Localization_pt_BR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ações.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Aplicação.
        /// </summary>
        internal static string ApplicationMN {
            get {
                return ResourceManager.GetString("ApplicationMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro na tentativa de aprovar o cliente..
        /// </summary>
        internal static string ClientApproveErrorMSG {
            get {
                return ResourceManager.GetString("ClientApproveErrorMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem certeza que deseja apagar este cliente?.
        /// </summary>
        internal static string ClientDeleteConfirmationMSG {
            get {
                return ResourceManager.GetString("ClientDeleteConfirmationMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro na tentativa de processar a rejeição do cliente.
        /// </summary>
        internal static string ClientRejectErrorMSG {
            get {
                return ResourceManager.GetString("ClientRejectErrorMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computador.
        /// </summary>
        internal static string Computer {
            get {
                return ResourceManager.GetString("Computer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambiente.
        /// </summary>
        internal static string Environment {
            get {
                return ResourceManager.GetString("Environment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sair.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Sair.
        /// </summary>
        internal static string ExitMN {
            get {
                return ResourceManager.GetString("ExitMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computador.
        /// </summary>
        internal static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta Usada.
        /// </summary>
        internal static string LoggedAccount {
            get {
                return ResourceManager.GetString("LoggedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrar.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seu processo de entrada falhou..
        /// </summary>
        internal static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máquina.
        /// </summary>
        internal static string Machine {
            get {
                return ResourceManager.GetString("Machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sua aplicação não foi registrada. Por favor solicite ao administrador que autorize a aplicação com o ID:.
        /// </summary>
        internal static string NoRegistrationMSG {
            get {
                return ResourceManager.GetString("NoRegistrationMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seu registro não foi aceito.
        /// </summary>
        internal static string NotAccepted {
            get {
                return ResourceManager.GetString("NotAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este método ainda não foi implementado..
        /// </summary>
        internal static string NotImplementedMSG {
            get {
                return ResourceManager.GetString("NotImplementedMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistema Operacional.
        /// </summary>
        internal static string OperationalSystem {
            get {
                return ResourceManager.GetString("OperationalSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro tentando registrar a sua aplicação com o servidor..
        /// </summary>
        internal static string RegistrationErrorMSG {
            get {
                return ResourceManager.GetString("RegistrationErrorMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O registro do seu aplicativo ainda não foi aceito por um administrador. ID:.
        /// </summary>
        internal static string RegistrationNotAcceptedMSG {
            get {
                return ResourceManager.GetString("RegistrationNotAcceptedMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil.
        /// </summary>
        internal static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor selecione o seu método de autenticação..
        /// </summary>
        internal static string SelectAuthenticationMSG {
            get {
                return ResourceManager.GetString("SelectAuthenticationMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servidor.
        /// </summary>
        internal static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistema.
        /// </summary>
        internal static string Sys {
            get {
                return ResourceManager.GetString("Sys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerta.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bem-vindo ao SRGUI Client..
        /// </summary>
        internal static string WelcomeMSG {
            get {
                return ResourceManager.GetString("WelcomeMSG", resourceCulture);
            }
        }
    }
}
